# Deliverable 2. 
Create a Customer Travel Destinations Map

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Weather
0,0,Isangel,VU,-19.55,169.27,74.52,82,14,9.48,few clouds
1,1,Mitsamiouli,KM,-11.38,43.28,79.02,73,2,4.74,clear sky
2,2,Lavrentiya,RU,65.58,-171.00,19.72,88,40,7.94,scattered clouds
3,3,Bredasdorp,ZA,-34.53,20.04,62.60,59,48,6.93,scattered clouds
4,4,Puerto Ayora,EC,-0.74,-90.35,77.00,73,40,9.17,scattered clouds

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 60
What is the maximum temperature you would like for your trip? 80

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & 
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Weather
0,0,Isangel,VU,-19.55,169.27,74.52,82,14,9.48,few clouds
1,1,Mitsamiouli,KM,-11.38,43.28,79.02,73,2,4.74,clear sky
3,3,Bredasdorp,ZA,-34.53,20.04,62.60,59,48,6.93,scattered clouds
4,4,Puerto Ayora,EC,-0.74,-90.35,77.00,73,40,9.17,scattered clouds
10,10,Port Elizabeth,ZA,-33.92,25.57,64.40,82,90,10.29,overcast clouds
11,11,Makakilo City,US,21.35,-158.09,71.60,83,1,3.36,clear sky
12,12,Mahebourg,MU,-20.41,57.70,73.40,64,75,10.29,broken clouds
13,13,Kieta,PG,-6.22,155.63,79.36,77,97,6.17,moderate rain
15,15,Payakumbuh,ID,-0.22,100.63,71.78,90,100,1.54,overcast clouds
17,17,Kapaa,US,22.08,-159.32,71.60,94,75,4.70,broken clouds

In [5]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()
preferred_cities_df.notnull().sum()

City_ID            261
City               261
Country            258
Lat                261
Lng                261
Max Temp           261
Humidity           261
Cloudiness         261
Wind Speed         261
Current Weather    261
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
preferred_cities_df_2 = preferred_cities_df.dropna()
preferred_cities_df_2.notnull().sum()
preferred_cities_df_2.info()
preferred_cities_df_2.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 258 entries, 0 to 676
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   City_ID          258 non-null    int64
 1   City             258 non-null    object
 2   Country          258 non-null    object
 3   Lat              258 non-null    float64
 4   Lng              258 non-null    float64
 5   Max Temp         258 non-null    float64
 6   Humidity         258 non-null    int64
 7   Cloudiness       258 non-null    int64
 8   Wind Speed       258 non-null    float64
 9   Current Weather  258 non-null    object
dtypes: float64(4), int64(3), object(3)
memory usage: 22.2+ KB

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Weather
0,0,Isangel,VU,-19.55,169.27,74.52,82,14,9.48,few clouds
1,1,Mitsamiouli,KM,-11.38,43.28,79.02,73,2,4.74,clear sky
3,3,Bredasdorp,ZA,-34.53,20.04,62.60,59,48,6.93,scattered clouds
4,4,Puerto Ayora,EC,-0.74,-90.35,77.00,73,40,9.17,scattered clouds
10,10,Port Elizabeth,ZA,-33.92,25.57,64.40,82,90,10.29,overcast clouds

In [7]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Weather", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Weather,Lat,Lng,Hotel Name
0,Isangel,VU,74.52,few clouds,-19.55,169.27,
1,Mitsamiouli,KM,79.02,clear sky,-11.38,43.28,
3,Bredasdorp,ZA,62.60,scattered clouds,-34.53,20.04,
4,Puerto Ayora,EC,77.00,scattered clouds,-0.74,-90.35,
10,Port Elizabeth,ZA,64.40,overcast clouds,-33.92,25.57,
11,Makakilo City,US,71.60,clear sky,21.35,-158.09,
12,Mahebourg,MU,73.40,broken clouds,-20.41,57.70,
13,Kieta,PG,79.36,moderate rain,-6.22,155.63,
15,Payakumbuh,ID,71.78,overcast clouds,-0.22,100.63,
17,Kapaa,US,71.60,broken clouds,22.08,-159.32,

In [8]:
# 6a. Set parameters to search for hotels with 5000 meters
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame
for index, row in hotel_df.iterrows():
    
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")
        pass

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [9]:
# 7. Drop the rows where there is no Hotel Name
hotel_df["Hotel Name"].isnull()
clean_hotel_df = hotel_df
clean_hotel_df["Hotel Name"] = hotel_df["Hotel Name"].dropna()

In [10]:
clean_hotel_df

,City,Country,Max Temp,Current Weather,Lat,Lng,Hotel Name
0,Isangel,VU,74.52,few clouds,-19.55,169.27,Volcano Sea View Tree House
1,Mitsamiouli,KM,79.02,clear sky,-11.38,43.28,Foyer ADM
3,Bredasdorp,ZA,62.60,scattered clouds,-34.53,20.04,Bredasdorp Country Manor
4,Puerto Ayora,EC,77.00,scattered clouds,-0.74,-90.35,Finch Bay Galapagos Hotel
10,Port Elizabeth,ZA,64.40,overcast clouds,-33.92,25.57,39 On Nile Guest House
...,...,...,...,...,...,...,...
662,Touho,NC,76.01,few clouds,-20.78,165.23,Auberge Timay Evasion
663,Sa Kaeo,TH,71.19,overcast clouds,13.75,102.33,บ้านร่มฉัตร รีสอร์ท
669,Yeppoon,AU,73.40,clear sky,-23.13,150.73,Villa Mar Colina
672,Durazno,UY,78.80,broken clouds,-33.41,-56.50,Hotel Santa Cristina
676,Creel,MX,60.13,clear sky,27.75,-107.63,The Lodge at Creel Hotel & SPA

In [11]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"

# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [12]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [13]:
# 11a. Add a marker layer for each city to the map. 
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))